-- | raw input data such as names

module Data where
import Test.QuickCheck

-- | Creates a Gen String of names
firstname
  = ["Toto"
    ,"Harald"
    ,"Sam"
    ,"Rasmus"
    ,"Melvin"
    ,"Martin"
    ,"Anas"
    ,"Tore"
    ,"Simon"
    ]
surname
  = ["Roomi"
    ,"Olin"
    ,"Shahriari"
    ,"Craelius"
    ,"Jakobsson"
    ,"Lindefors"
    ,"Almawed"
    ,"Stenberg"
    ,"Rosén"
    ,"Maltin"
    ]
emaildomain = "@kth.se"

tag
  = ["#love"
    ,"#instagood"
    ,"#fashion"
    ,"#photooftheday"
    ,"#photography"
    ,"#art"
    ,"#beautiful"
    ,"#nature"
    ,"#picoftheday"
    ,"#happy"
    ,"#follow"
    ,"#travel"
    ,"#cute"
    ,"#style"
    ,"#instadaily"
    ,"#tbt"
    ,"#followme"
    ,"#summer"
    ,"#beauty"
    ,"#fitness"
    ,"#like4like"
    ,"#food"
    ,"#instalike"
    ,"#photo"
    ,"#selfie"
    ,"#friends"
    ,"#music"
    ,"#smile"
    ,"#family"
    ,"#life"
    ,"#fun"
    ,"#girl"
    ,"#likeforlikes"
    ,"#motivation"
    ,"#lifestyle"
    ,"#likeforlike"
    ,"#sunset"
    ,"#amazing"
    ,"#nofilter"
    ,"#instamood"
    ,"#sun"
    ,"#follow4follow"
    ,"#inspiration"
    ,"#followforfollow"
    ,"#instapic"
    ,"#bestoftheday"
    ,"#cool"
    ,"#swag"
    ,"#night"
    ,"#happybirthday"
    ,"#smallbusiness"
    ,"#business"
    ,"#entrepreneur"
    ,"#socialmedia"
    ,"#digitalmarketing"
    ,"#sales"
    ,"#tech"
    ,"#leadership"
    ,"#innovation"
    ,"#networking"
    ,"#SEO"
    ,"#contentmarketing"
    ,"#marketingstrategy"
    ,"#businesstips"
    ,"#startups"
    ,"#productivity"
    ,"#strategy"
    ,"#b2b"
    ,"#consulting"
    ,"#workplace"
    ,"#professionaldevelopment"
    ,"#leadgeneration"
    ,"#b2bmarketing"
    ,"#saas"
    ,"#thoughtleadership"
    ,"#explore"
    ,"#foodporn"
    ,"#foodie"
    ,"#instafood"
    ,"#instafashion"
    ,"#travelgram"
    ,"#shopping"
    ,"#homedecor"
    ,"#fashionista"
    ,"#instatravel"
    ,"#sale"
    ,"#shoplocal"
    ,"#summervibes"
    ,"#instabeauty"
    ,"#styleinspo"
    ,"#discount"
    ,"#instashop"
    ,"#healthAndwellness"
    ,"#instasale"
    ,"#productreview"
    ,"#b2c"
    ,"#instagram"
    ,"#followforfollowback"
    ,"#like"
    ,"#explorepage"
    ,"#fyp"
    ,"#daily"
    ,"#like4likes"
    ,"#instalove"
    ,"#instaphoto"
    ,"#likeforlikes"
    ,"#instacool"
    ,"#followers"
    ,"#comedy"
    ,"#like4follow"
    ,"#follow4followback"
    ,"#likeme"
    ,"#likesforlikes"
    ,"#dog"
    ,"#dogsofinstagram"
    ,"#dogs"
    ,"#instadog"
    ,"#doglover"
    ,"#dogoftheday"
    ,"#ilovemydog"
    ,"#rescuedog"
    ,"#doglove"
    ,"#dogphotography"
    ,"#dogmom"
    ,"#dogmodel"
    ,"#Dogsitting"
    ,"#Dogofinstagram"
    ,"#dogtraining"
    ,"#doglife"
    ,"#Doggrooming"
    ,"#Doginstagram"
    ,"#doginfluencer"
    ,"#dogboarding"
    ,"#dogsmile"
    ,"#Dogselfie"
    ,"#dogpics"
    ,"#doggram"
    ,"#Dogadventures"
    ,"#fitness"
    ,"#gym"
    ,"#workout"
    ,"#health"
    ,"#fitnessmotivation"
    ,"#bodybuilding"
    ,"#healthy"
    ,"#yoga"
    ,"#running"
    ,"#body"
    ,"#run"
    ,"#fitnessmodel"
    ,"#gymmotivation"
    ,"#cardio"
    ,"#fitnessaddict"
    ,"#fitnessjourney"
    ,"#getfit"
    ,"#fitmom"
    ,"#workoutmotivation"
    ,"#gymrat"
    ,"#fitnesslifestyle"
    ,"#yogainspiration"
    ,"#sweat"
    ,"#strengthtraining"
    ,"#gymgirl"
    ,"#art"
    ,"#photography"
    ,"#artist"
    ,"#drawing"
    ,"#artwork"
    ,"#digitalart"
    ,"#artistsoninstagram"
    ,"#draw"
    ,"#instaart"
    ,"#artoftheday"
    ,"#contemporaryart"
    ,"#paint"
    ,"#abstractart"
    ,"#artgallery"
    ,"#artistic"
    ,"#artofinstagram"
    ,"#artcollector"
    ,"#modernart"
    ,"#tattooart"
    ,"#urbanart"
    ,"#picsart"
    ,"#artists"
    ,"#artlover"
    ,"#artdaily"
    ,"#artjournal"
    ]


address
  = ["Brinellvägen 1"
    ,"Brinellvägen 2"
    ,"Brinellvägen 3"
    ,"Brinellvägen 4"
    ,"Brinellvägen 5"
    ,"Brinellvägen 6"
    ,"Brinellvägen 7"
    ,"Brinellvägen 8"
    ,"Brinellvägen 9"
    ,"Brinellvägen 10"
    ,"Brinellvägen 11"
    ,"Brinellvägen 12"
    ,"Brinellvägen 13"
    ,"Brinellvägen 14"
    ,"Brinellvägen 15"
    ,"Brinellvägen 16"
    ,"Brinellvägen 17"
    ,"Brinellvägen 18"
    ,"Brinellvägen 19"
    ,"Brinellvägen 20"
    ,"Brinellvägen 21"
    ,"Brinellvägen 22A"
    ,"Brinellvägen 22B"
    ,"Brinellvägen 22C"
    ,"Brinellvägen 22D"
    ,"Brinellvägen 22E"
    ,"Brinellvägen 23"
    ,"Brinellvägen 24A"
    ,"Brinellvägen 24B"
    ,"Brinellvägen 25"
    ,"Brinellvägen 26"
    ,"Brinellvägen 28A"
    ,"Brinellvägen 28B"
    ,"Brinellvägen 28C"
    ,"Brinellvägen 30"
    ,"Brinellvägen 31"
    ,"Brinellvägen 32"
    ,"Brinellvägen 33"
    ,"Brinellvägen 34"
    ,"Brinellvägen 35"
    ,"Brinellvägen 36"
    ,"Brinellvägen 37"
    ,"Brinellvägen 38"
    ,"Brinellvägen 39"
    ,"Brinellvägen 40"
    ,"Brinellvägen 41"
    ,"Brinellvägen 42"
    ,"Brinellvägen 43"
    ,"Brinellvägen 44"
    ,"Brinellvägen 45"
    ,"Brinellvägen 46"
    ,"Brinellvägen 47"
    ,"Brinellvägen 48"
    ,"Brinellvägen 49"
    ,"Brinellvägen 50"
    ,"Brinellvägen 51"
    ,"Brinellvägen 52"
    ,"Brinellvägen 53"
    ,"Brinellvägen 54"
    ,"Brinellvägen 55"
    ,"Brinellvägen 56"
    ,"Brinellvägen 57"
    ,"Brinellvägen 58"
    ,"Brinellvägen 59"
    ,"Brinellvägen 60"
    ,"Brinellvägen 61"
    ,"Brinellvägen 62"
    ,"Brinellvägen 63"
    ,"Brinellvägen 64A"
    ,"Brinellvägen 64B"
    ,"Brinellvägen 65"
    ,"Brinellvägen 66"
    ,"Brinellvägen 67"
    ,"Brinellvägen 68"
    ,"Brinellvägen 69"
    ,"Brinellvägen 70"
    ,"Brinellvägen 71"
    ,"Brinellvägen 72"
    ,"Brinellvägen 73"
    ,"Brinellvägen 74"
    ,"Brinellvägen 75"
    ,"Brinellvägen 76"
    ,"Brinellvägen 77"
    ,"Brinellvägen 78"
    ,"Brinellvägen 79"
    ,"Brinellvägen 80"
    ,"Brinellvägen 81"
    ,"Brinellvägen 82"
    ,"Brinellvägen 83"
    ,"Brinellvägen 84"
    ,"Brinellvägen 85"
    ,"Brinellvägen 86"
    ,"Brinellvägen 87"
    ,"Brinellvägen 88"
    ,"Brinellvägen 89"
    ,"Drottning Kristinas väg 1"
    ,"Drottning Kristinas väg 1T"
    ,"Drottning Kristinas väg 2"
    ,"Drottning Kristinas väg 3"
    ,"Drottning Kristinas väg 4"
    ,"Drottning Kristinas väg 5"
    ,"Drottning Kristinas väg 6"
    ,"Drottning Kristinas väg 7"
    ,"Drottning Kristinas väg 8"
    ,"Drottning Kristinas väg 9"
    ,"Drottning Kristinas väg 10"
    ,"Drottning Kristinas väg 11"
    ,"Drottning Kristinas väg 12"
    ,"Drottning Kristinas väg 13"
    ,"Drottning Kristinas väg 13A"
    ,"Drottning Kristinas väg 14"
    ,"Drottning Kristinas väg 15"
    ,"Drottning Kristinas väg 16"
    ,"Drottning Kristinas väg 17"
    ,"Drottning Kristinas väg 18"
    ,"Drottning Kristinas väg 19"
    ,"Drottning Kristinas väg 20"
    ,"Drottning Kristinas väg 21"
    ,"Drottning Kristinas väg 22"
    ,"Drottning Kristinas väg 23"
    ,"Drottning Kristinas väg 24"
    ,"Drottning Kristinas väg 25"
    ,"Drottning Kristinas väg 26"
    ,"Drottning Kristinas väg 27"
    ,"Drottning Kristinas väg 27A"
    ,"Drottning Kristinas väg 28"
    ,"Drottning Kristinas väg 29"
    ,"Drottning Kristinas väg 30"
    ,"Drottning Kristinas väg 30A"
    ,"Drottning Kristinas väg 31"
    ,"Drottning Kristinas väg 31N"
    ,"Drottning Kristinas väg 32"
    ,"Drottning Kristinas väg 33"
    ,"Drottning Kristinas väg 33A"
    ,"Drottning Kristinas väg 33B"
    ,"Drottning Kristinas väg 33C"
    ,"Drottning Kristinas väg 33D"
    ,"Drottning Kristinas väg 33X"
    ,"Drottning Kristinas väg 34"
    ,"Drottning Kristinas väg 34A"
    ,"Drottning Kristinas väg 34B"
    ,"Drottning Kristinas väg 34C"
    ,"Drottning Kristinas väg 34D"
    ,"Drottning Kristinas väg 35"
    ,"Drottning Kristinas väg 36"
    ,"Drottning Kristinas väg 36A"
    ,"Drottning Kristinas väg 36B"
    ,"Drottning Kristinas väg 37"
    ,"Drottning Kristinas väg 38"
    ,"Drottning Kristinas väg 39"
    ,"Drottning Kristinas väg 40"
    ,"Drottning Kristinas väg 41"
    ,"Drottning Kristinas väg 42"
    ,"Drottning Kristinas väg 43"
    ,"Drottning Kristinas väg 43A"
    ,"Drottning Kristinas väg 43B"
    ,"Drottning Kristinas väg 43C"
    ,"Drottning Kristinas väg 43D"
    ,"Drottning Kristinas väg 43E"
    ,"Drottning Kristinas väg 43F"
    ,"Drottning Kristinas väg 43G"
    ,"Drottning Kristinas väg 43H"
    ,"Drottning Kristinas väg 43I"
    ,"Drottning Kristinas väg 43J"
    ,"Drottning Kristinas väg 43K"
    ,"Drottning Kristinas väg 43L"
    ,"Drottning Kristinas väg 43M"
    ,"Drottning Kristinas väg 43N"
    ,"Drottning Kristinas väg 43O"
    ,"Drottning Kristinas väg 43P"
    ,"Drottning Kristinas väg 43Q"
    ,"Drottning Kristinas väg 43R"
    ,"Drottning Kristinas väg 43S"
    ,"Drottning Kristinas väg 43T"
    ,"Drottning Kristinas väg 43U"
    ,"Drottning Kristinas väg 43V"
    ,"Drottning Kristinas väg 43W"
    ,"Drottning Kristinas väg 43X"
    ,"Drottning Kristinas väg 43Y"
    ,"Drottning Kristinas väg 43Z"
    ,"Drottning Kristinas väg 44"
    ,"Drottning Kristinas väg 45"
    ,"Drottning Kristinas väg 45A"
    ,"Drottning Kristinas väg 46"
    ,"Drottning Kristinas väg 47"
    ,"Drottning Kristinas väg 48"
    ,"Drottning Kristinas väg 49"
    ,"Drottning Kristinas väg 50"
    ,"Drottning Kristinas väg 51"
    ,"Drottning Kristinas väg 52"
    ,"Drottning Kristinas väg 53"
    ,"Drottning Kristinas väg 53A"
    ,"Drottning Kristinas väg 53B"
    ,"Drottning Kristinas väg 53C"
    ,"Drottning Kristinas väg 54"
    ,"Drottning Kristinas väg 55"
    ,"Drottning Kristinas väg 56"
    ,"Drottning Kristinas väg 57"
    ,"Drottning Kristinas väg 58"
    ,"Drottning Kristinas väg 59"
    ,"Drottning Kristinas väg 60"
    ,"Drottning Kristinas väg 61"
    ,"Drottning Kristinas väg 61B"
    ,"Drottning Kristinas väg 61C"
    ,"Drottning Kristinas väg 62"
    ,"Drottning Kristinas väg 63"
    ,"Drottning Kristinas väg 63A"
    ,"Drottning Kristinas väg 63B"
    ,"Drottning Kristinas väg 63C"
    ,"Drottning Kristinas väg 63D"
    ,"Drottning Kristinas väg 63E"
    ,"Drottning Kristinas väg 63F"
    ,"Drottning Kristinas väg 63G"
    ,"Drottning Kristinas väg 63H"
    ,"Drottning Kristinas väg 63I"
    ,"Drottning Kristinas väg 63J"
    ,"Drottning Kristinas väg 63K"
    ,"Drottning Kristinas väg 63L"
    ,"Drottning Kristinas väg 63M"
    ,"Drottning Kristinas väg 63N"
    ,"Drottning Kristinas väg 63O"
    ,"Drottning Kristinas väg 63P"
    ,"Drottning Kristinas väg 63Q"
    ,"Drottning Kristinas väg 63R"
    ,"Drottning Kristinas väg 63S"
    ,"Drottning Kristinas väg 63T"
    ,"Drottning Kristinas väg 63U"
    ,"Drottning Kristinas väg 63V"
    ,"Drottning Kristinas väg 63W"
    ,"Drottning Kristinas väg 63X"
    ,"Drottning Kristinas väg 63Y"
    ,"Drottning Kristinas väg 63Z"
    ,"Drottning Kristinas väg 64"
    ,"Drottning Kristinas väg 65"
    ,"Drottning Kristinas väg 66"
    ,"Drottning Kristinas väg 67"
    ,"Drottning Kristinas väg 67B"
    ,"Drottning Kristinas väg 68"
    ,"Drottning Kristinas väg 69"
    ,"Drottning Kristinas väg 70"
    ,"Drottning Kristinas väg 71"
    ,"Drottning Kristinas väg 72"
    ,"Drottning Kristinas väg 73"
    ,"Drottning Kristinas väg 74"
    ,"Drottning Kristinas väg 75"
    ,"Drottning Kristinas väg 76"
    ,"Drottning Kristinas väg 77"
    ,"Drottning Kristinas väg 78"
    ,"Drottning Kristinas väg 79"
    ,"Drottning Kristinas väg 80"
    ,"Drottning Kristinas väg 81"
    ,"Drottning Kristinas väg 82"
    ,"Drottning Kristinas väg 83"
    ,"Drottning Kristinas väg 84"
    ,"Drottning Kristinas väg 85"
    ,"Drottning Kristinas väg 86"
    ,"Drottning Kristinas väg 87"
    ,"Drottning Kristinas väg 88"
    ,"Drottning Kristinas väg 89"
    ,"Drottning Kristinas väg 90"
    ,"Drottning Kristinas väg 91"
    ,"Drottning Kristinas väg 92"
    ,"Drottning Kristinas väg 93"
    ,"Drottning Kristinas väg 94"
    ,"Drottning Kristinas väg 95"
    ,"Lindstedtsvägen 1"
    ,"Lindstedtsvägen 2"
    ,"Lindstedtsvägen 3"
    ,"Lindstedtsvägen 4"
    ,"Lindstedtsvägen 5"
    ,"Lindstedtsvägen 6"
    ,"Lindstedtsvägen 7"
    ,"Lindstedtsvägen 8"
    ,"Lindstedtsvägen 9"
    ,"Lindstedtsvägen 10"
    ,"Lindstedtsvägen 11"
    ,"Lindstedtsvägen 12"
    ,"Lindstedtsvägen 13"
    ,"Lindstedtsvägen 14"
    ,"Lindstedtsvägen 15"
    ,"Lindstedtsvägen 16"
    ,"Lindstedtsvägen 17"
    ,"Lindstedtsvägen 18"
    ,"Lindstedtsvägen 19"
    ,"Lindstedtsvägen 20"
    ,"Lindstedtsvägen 21"
    ,"Lindstedtsvägen 22"
    ,"Lindstedtsvägen 23"
    ,"Lindstedtsvägen 24"
    ,"Lindstedtsvägen 25"
    ,"Lindstedtsvägen 25A"
    ,"Lindstedtsvägen 26"
    ,"Lindstedtsvägen 27"
    ,"Lindstedtsvägen 28"
    ,"Lindstedtsvägen 29"
    ,"Lindstedtsvägen 30"
    ,"Malvinas väg 3"
    ,"Malvinas väg 4"
    ,"Malvinas väg 5"
    ,"Malvinas väg 6"
    ,"Malvinas väg 7"
    ,"Malvinas väg 8"
    ,"Malvinas väg 9"
    ,"Malvinas väg 10"
    ,"Malvinas väg 11"
    ,"Malvinas väg 12"
    ,"Malvinas väg 13"
    ,"Malvinas väg 14"
    ,"Malvinas väg 15"
    ,"Malvinas väg 16"
    ,"Malvinas väg 17"
    ,"Malvinas väg 18"
    ,"Malvinas väg 19"
    ,"Malvinas väg 20"
    ,"Osquars backe 1"
    ,"Osquars backe 2"
    ,"Osquars backe 3"
    ,"Osquars backe 4"
    ,"Osquars backe 5"
    ,"Osquars backe 6"
    ,"Osquars backe 7"
    ,"Osquars backe 8"
    ,"Osquars backe 9"
    ,"Osquars backe 10"
    ,"Osquars backe 11"
    ,"Osquars backe 12"
    ,"Osquars backe 13"
    ,"Osquars backe 14"
    ,"Osquars backe 15"
    ,"Osquars backe 16"
    ,"Osquars backe 17"
    ,"Osquars backe 18"
    ,"Osquars backe 19"
    ,"Osquars backe 20"
    ,"Osquars backe 21"
    ,"Osquars backe 22"
    ,"Osquars backe 23"
    ,"Osquars backe 24"
    ,"Osquars backe 25"
    ,"Osquars backe 26"
    ,"Osquars backe 27"
    ,"Osquars backe 28"
    ,"Osquars backe 29"
    ,"Osquars backe 30"
    ,"Osquars backe 31"
    ,"Teknikringen 1"
    ,"Teknikringen 2"
    ,"Teknikringen 3"
    ,"Teknikringen 4"
    ,"Teknikringen 5"
    ,"Teknikringen 6"
    ,"Teknikringen 6A"
    ,"Teknikringen 7"
    ,"Teknikringen 8"
    ,"Teknikringen 9"
    ,"Teknikringen 10"
    ,"Teknikringen 10A"
    ,"Teknikringen 10B"
    ,"Teknikringen 11"
    ,"Teknikringen 12"
    ,"Teknikringen 13"
    ,"Teknikringen 14"
    ,"Teknikringen 15"
    ,"Teknikringen 16"
    ,"Teknikringen 17"
    ,"Teknikringen 18"
    ,"Teknikringen 19"
    ,"Teknikringen 20"
    ,"Teknikringen 20A"
    ,"Teknikringen 21"
    ,"Teknikringen 22"
    ,"Teknikringen 23"
    ,"Teknikringen 24"
    ,"Teknikringen 25"
    ,"Teknikringen 26"
    ,"Teknikringen 27"
    ,"Teknikringen 28"
    ,"Teknikringen 29"
    ,"Teknikringen 30"
    ,"Teknikringen 31"
    ,"Teknikringen 32"
    ,"Teknikringen 33"
    ,"Teknikringen 34"
    ,"Teknikringen 35"
    ,"Teknikringen 36"
    ,"Teknikringen 37"
    ,"Teknikringen 37A"
    ,"Teknikringen 38"
    ,"Teknikringen 39"
    ,"Teknikringen 40"
    ,"Teknikringen 41"
    ,"Teknikringen 42"
    ,"Teknikringen 43"
    ,"Teknikringen 44"
    ,"Teknikringen 45"
    ,"Teknikringen 46"
    ,"Teknikringen 47"
    ,"Teknikringen 48"
    ,"Teknikringen 49"
    ,"Teknikringen 50"
    ,"Teknikringen 51"
    ,"Teknikringen 52"
    ,"Teknikringen 53"
    ,"Teknikringen 54"
    ,"Teknikringen 55"
    ,"Teknikringen 56"
    ,"Teknikringen 57"
    ,"Teknikringen 58"
    ,"Teknikringen 58A"
    ,"Teknikringen 59"
    ,"Teknikringen 60"
    ,"Teknikringen 61"
    ,"Teknikringen 62"
    ,"Teknikringen 63"
    ,"Teknikringen 64"
    ,"Teknikringen 65"
    ,"Teknikringen 66"
    ,"Teknikringen 67"
    ,"Teknikringen 68"
    ,"Teknikringen 68A"
    ,"Teknikringen 69"
    ,"Teknikringen 70"
    ,"Teknikringen 70A"
    ,"Teknikringen 71"
    ,"Teknikringen 72"
    ,"Teknikringen 72A"
    ,"Teknikringen 72B"
    ,"Teknikringen 72C"
    ,"Teknikringen 72D"
    ,"Teknikringen 73"
    ,"Teknikringen 74"
    ,"Teknikringen 74A"
    ,"Teknikringen 74B"
    ,"Teknikringen 74C"
    ,"Teknikringen 74D"
    ,"Teknikringen 74E"
    ,"Teknikringen 75"
    ,"Teknikringen 76"
    ,"Teknikringen 77"
    ,"Teknikringen 78"
    ,"Teknikringen 78A"
    ,"Teknikringen 78B"
    ,"Teknikringen 78C"
    ,"Uggleviksvägen 10"
    ,"Valhallavägen 61"
    ,"Valhallavägen 73A"
    ,"Valhallavägen 75"
    ,"Valhallavägen 76"
    ,"Valhallavägen 77"
    ,"Valhallavägen 77A"
    ,"Valhallavägen 77B"
    ,"Valhallavägen 77C"
    ,"Valhallavägen 77D"
    ,"Valhallavägen 77T"
    ,"Valhallavägen 79"
    ,"Valhallavägen 80"
    ,"Valhallavägen 81"
    ,"Valhallavägen 82"
    ,"Valhallavägen 83"
    ,"Valhallavägen 91"
    ,"Valhallavägen 91A"
    ,"Valhallavägen 91B"
    ,"Valhallavägen 91C"
    ,"Valhallavägen 91D"
    ,"Valhallavägen 91E"
    ,"Valhallavägen 91F"
    ,"Valhallavägen 91G"
    ,"Valhallavägen 91H"
    ,"Valhallavägen 91K"
    ,"Valhallavägen 91L"
    ,"Valhallavägen 91M"
    ,"Valhallavägen 91O"
    ,"Valhallavägen 91R"
    ,"Valhallavägen 91T"
    ,"Valhallavägen 95"
    ]


adjective
  = ["Funny"
    ,"Fun"
    ,"Serious"
    ,"Comedic"
    ,"Summer vibes"
    ,"Delightful"
    ,"Weird"
    ,"Crazy"
    ,"Hot"
    ,"Sexy"
    ,"Extravagant"
    ,"Kinky"
    ,"Naked"
    ,"Fancy"
    ]
activity
 = ["wine tasting"
   ,"dinner party"
   ,"pub"
   ,"life drawing"
   ,"arts and crafts"
   ,"movie viewing"
   ,"board games"
   ,"party"
   ,"pizza party"
   ,"rave"
   ,"tenta pub"
   ]
